services:
  scrap:
    build: .
    container_name: scrap
    ports:
      - "8000:8000"

    depends_on:
      - db
  db:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    container_name: db

   
    



