# Generated by Django 4.2.7 on 2024-02-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_usd',
            field=models.IntegerField(null=True),
        ),
    ]
